### ISSUE TITLE
how to add -L or -lpthread ?

### ISSUE THREAD

**Issue by awzhgw** [minio/c2goasm#20]
how to add -L or -lpthread ?

**Comment by awzhgw** [comment]
How to join other dynamic libraries? Is my c language will call other dynamic libraries, what should I do?


[root@A01-R21-I252-5-2X642M2 rdma]# go build          
# _/home/guowl/rdma
./socket_amd64.s:22: undefined label close
./socket_amd64.s:108: undefined label close
./socket_amd64.s:145: undefined label close
./socket_amd64.s:182: undefined label close
./socket_amd64.s:218: undefined label close
./socket_amd64.s:254: undefined label close
./socket_amd64.s:369: undefined label close

the close is c socket close function

**Comment by fwessels** [comment]
This is not supported (see also https://github.com/minio/c2goasm#limitations).
Generally speaking the function to be "assemblified" needs to be a stand-alone (inlineable) function with fixed stack requirements. So calling other functions or doing threading with in the C-world is not allowed.

**Comment by kannappanr** [comment]
@awzhgw Closing this issue as answered
