### ISSUE TITLE
Q: c2goasm

### ISSUE THREAD

**Issue by ivanjaros** [minio/c2goasm#28]
Sorry for posting here but c2goasm does not have enabled issues and this seems like the "main" project here.

I just found the c2goasm project by accident and am wondering if it is capable for making ffmpeg library go-native?

**Comment by fwessels** [comment]
No, that is not going to work, that is much too big a library for it.

Generally speaking c2goasm can be used to port "leaf" functions to golang assembly, meaning functions that do not  call other functions (or fully inline them). Also functions that would malloc()/realloc() structures etc. will not work as the C memory management is not compatible with Golang's garbage collector.

So the best you may be able to do is port small bits and pieces to Go, but that would still leave a lot of code to be ported in another fashion.
